version: "2.3"
services:
  app:
    build:
      context: ./
      dockerfile: ./builds/docker/Dockerfile.app-deploy-full
      args:
        APP_DOCKER_IMAGE: ${APP_DOCKER_IMAGE}
        COMPOSER_AUTH: ${COMPOSER_AUTH}
    image: ${APP_CI_DOCKER_IMAGE}:${APP_CI_DOCKER_VERSION}
    environment:
      - PHP_XDEBUG_ENABLED=true
    command:
      - "sleep"
      - "7200"
  mysql:
    command:
      [
        "--explicit_defaults_for_timestamp=1",
        "--key_buffer_size=16K",
        "--sort_buffer_size=64K",
        "--read_buffer_size=256K",
        "--read_rnd_buffer_size=256K",
        "--net_buffer_length=2K",
        "--innodb_buffer_pool_size=96M",
        "--innodb_buffer_pool_instances=1",
        "--innodb_flush_log_at_trx_commit=0",
        "--innodb-doublewrite=0",
        "--innodb_file_format=Barracuda",
        "--innodb_log_file_size=10M",
        "--innodb_large_prefix",
        "--innodb_support_xa=0",
        "--innodb_checksum_algorithm=NONE",
        "--sync_frm=0",
        "--performance_schema=OFF",
        "--skip-name-resolve",
        "--skip-host-cache",
      ]
    volumes:
      - type: tmpfs
        target: /var/lib/mysql
